package com.windcoder.qycms.system.entity;

import java.util.Date;

public class CommentAgent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_comment_agent.id
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_comment_agent.target_id
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    private Long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_comment_agent.target_type
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    private String targetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_comment_agent.target_name
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    private String targetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_comment_agent.enabled
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_comment_agent.created_by
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_comment_agent.last_modified_by
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    private Long lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_comment_agent.created_date
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sns_comment_agent.last_modified_date
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    private Date lastModifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_comment_agent.id
     *
     * @return the value of sns_comment_agent.id
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_comment_agent.id
     *
     * @param id the value for sns_comment_agent.id
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_comment_agent.target_id
     *
     * @return the value of sns_comment_agent.target_id
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_comment_agent.target_id
     *
     * @param targetId the value for sns_comment_agent.target_id
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_comment_agent.target_type
     *
     * @return the value of sns_comment_agent.target_type
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public String getTargetType() {
        return targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_comment_agent.target_type
     *
     * @param targetType the value for sns_comment_agent.target_type
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_comment_agent.target_name
     *
     * @return the value of sns_comment_agent.target_name
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_comment_agent.target_name
     *
     * @param targetName the value for sns_comment_agent.target_name
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_comment_agent.enabled
     *
     * @return the value of sns_comment_agent.enabled
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_comment_agent.enabled
     *
     * @param enabled the value for sns_comment_agent.enabled
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_comment_agent.created_by
     *
     * @return the value of sns_comment_agent.created_by
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_comment_agent.created_by
     *
     * @param createdBy the value for sns_comment_agent.created_by
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_comment_agent.last_modified_by
     *
     * @return the value of sns_comment_agent.last_modified_by
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public Long getLastModifiedBy() {
        return lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_comment_agent.last_modified_by
     *
     * @param lastModifiedBy the value for sns_comment_agent.last_modified_by
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public void setLastModifiedBy(Long lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_comment_agent.created_date
     *
     * @return the value of sns_comment_agent.created_date
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_comment_agent.created_date
     *
     * @param createdDate the value for sns_comment_agent.created_date
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sns_comment_agent.last_modified_date
     *
     * @return the value of sns_comment_agent.last_modified_date
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sns_comment_agent.last_modified_date
     *
     * @param lastModifiedDate the value for sns_comment_agent.last_modified_date
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", targetId=").append(targetId);
        sb.append(", targetType=").append(targetType);
        sb.append(", targetName=").append(targetName);
        sb.append(", enabled=").append(enabled);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", lastModifiedBy=").append(lastModifiedBy);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", lastModifiedDate=").append(lastModifiedDate);
        sb.append("]");
        return sb.toString();
    }
}