server:
  port: 8000
  session:
    timeout: 3600
    cookie:
      http-only: true

spring:
  main:
    allow-bean-definition-overriding: true
  http:
    multipart:
      max-file-size: 10737418244
      max-request-size: 10737418244
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type:  com.alibaba.druid.pool.DruidDataSource
    url: jdbc:MySQL://127.0.0.1:3306/qycmsblog?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
    username: ENC(BWo944CV+CTg1tgYUUKW5x8Wy4MCYYUcZUYILyWBPriOHlORBCPXdL07LL6Fkh17)
    password: ENC(7tfUDlUoYeZARZOcVBBjBED2k6sSXVgWQGnx3iGX9AvOQQlUCtiRqYMUtuJEnZQGRCZO4x+LL9jbN4yT8aFOeQ==)
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    asyncInit: true
  redis:
    host: ENC(J3RLrcQUDH6wd8UvPDR3xRgMRa7YNGm6bwj8KJwS+zNOnTba326wesRMkRv9Y5Hw)
    password: ENC(0GOZrQYj6325m4K9Tu5UfocFQA1qpeuLdVAusUi4FYLS+nCgCYe9OQXMDV8wg974PFD9XEcvw9Hr+jiHVSJ2og==)
    port: 6380
    database: 8
    timeout: 2000s
    Jedis:
      pool:
        max-idle: 5
        max-active: 3
        max-wait: 60000
        min-idle: 1
    lettuce:
      pool:
        max-idle: 10
        max-active: 8
        max-wait: 60000
        min-idle: 3
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler #调度器的实例名
            instanceId: AUTO #调度器编号自动生成
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_ #数据库表名前缀
            isClustered: true #开启分布式部署
            clusterCheckinInterval: 10000   #分布式节点有效性检查时间间隔,单位:秒
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool  #自带的线程池实现类
            threadCount: 10  #开启10个线程
            threadPriority: 5 #工作者线程的优先级
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
# mybatis
mybatis:
  mapper-locations: classpath*:/com/windcoder/**/repository/mybatis/mappers/**/*.xml,classpath*:/mappers/**/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#配置数据源加密的密钥
jasypt:
  encryptor:
    password: qwindcoderyAdmin
#用于控制mybatis打印sql，生产环境应更改为ERROR级别
logging:
  level:
    root: error
    com:
      windcoder:
        qycms: error

qy:
  token: SAkSgsuN
  minaToken: "#$#ywerdfqW$h"
  xmlPath: "/www/wwwroot/windcoder.com/qy-web/static"
