server:
  port: 8000
  session:
    timeout: 3600
    cookie:
      http-only: true

spring:
  main:
    allow-bean-definition-overriding: true
  http:
    multipart:
      max-file-size: 10737418244
      max-request-size: 10737418244
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type:  com.alibaba.druid.pool.DruidDataSource
    url: jdbc:MySQL://localhost:3306/qycmsdev?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    connection-init-sql: "SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;"
#    username: ENC(Sua21kW9AckGBtpW13LyF03e7aOjC2zE)
#    password: ENC(f+2+aW4Po3YqeQkXaccinw==)
#    username: winder
#    password: 123456
    username: qycmsdev
    password: DCZehzmeAiM5wtrc
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    asyncInit: true
  redis:
    host: ENC(e/prl+7EXAa9PmwCfoE1a0TP8LrSrfaCSgjwFMQreEYczuxSBdMuEsHtXDgCjSzL)
    password: ENC(j6n3ISryjfYIBLhG9SWIb6Vah2jySJ4zwypGVE2dl0ilm36KwUzpQqiwf/ST6BJ3)
    port: 6380
    database: 8
    timeout: 100000
    Jedis:
      pool:
        max-idle: 5
        max-active: 3
        max-wait: 60000
        min-idle: 1
    lettuce:
      pool:
        max-idle: 10
        max-active: 8
        max-wait: 60000
        min-idle: 3

# mybatis
mybatis:
  mapper-locations: classpath*:/com/windcoder/**/repository/mybatis/mappers/**/*.xml,classpath*:/mappers/**/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#配置数据源加密的密钥
jasypt:
  encryptor:
    password: windcoderAdmin
#用于控制mybatis打印sql，生产环境应更改为ERROR级别
logging:
  level:
    root: error
    com:
      windcoder:
        qycms: error

qy:
  token: o6lZQ


























