package com.windcoder.qycms.system.repository.mybatis;

import com.windcoder.qycms.system.entity.CommentAgent;
import com.windcoder.qycms.system.entity.CommentAgentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentAgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    long countByExample(CommentAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    int deleteByExample(CommentAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    int insert(CommentAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    int insertSelective(CommentAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    List<CommentAgent> selectByExample(CommentAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    CommentAgent selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") CommentAgent record, @Param("example") CommentAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    int updateByExample(@Param("record") CommentAgent record, @Param("example") CommentAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    int updateByPrimaryKeySelective(CommentAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sns_comment_agent
     *
     * @mbg.generated Sat Jul 11 17:58:44 CST 2020
     */
    int updateByPrimaryKey(CommentAgent record);
}